default_context:
  project_name: 'fastvis'
  project_slug: 'fastvis'
  domain_main: 'fastvis.netlify.app'
  domain_staging: 'stag.fastvis.netlify.app'
  docker_swarm_stack_name_main: 'fastvis-netlify-app'
  docker_swarm_stack_name_staging: 'stag-fastvis-netlify-app'
  secret_key: '147856fac1d718ecff56e5bcac4f77bc01b229604376e9b9b253e930a926885e'
  first_superuser: 'admin@fastvis.netlify.app'
  first_superuser_password: '2358BelethEl76!08'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastvis.netlfiy.app", "https://stag.fastvis.netlify.app", "https://fastvis.netlfiy.app", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastvis.netlify.app'
  postgres_password: 'fb61a60c875df6d6349dbda1f70d6e0add845c287c67601001c1f61634e91c4e'
  pgadmin_default_user: 'admin@fastvis.netlify.app'
  pgadmin_default_user_password: '2358BelethEl76!08'
  traefik_constraint_tag: 'fastvis.netlify.app'
  traefik_constraint_tag_staging: 'stag.fastvis.netlify.app'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:2358BelethEl76!08'
  sentry_dsn: ''
  docker_image_prefix: 'michaelwnau/fastvis'
  docker_image_backend: 'michaelwnau/fastvis/backend'
  docker_image_celeryworker: 'michaelwnau/fastvis/celeryworker'
  docker_image_frontend: 'michaelwnau/fastvis/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
